In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.12.0+cu130


In [3]:
# !nvidia-smi

# Intro to Tensors
A tensor is a multi-dimensional array which can run on a GPU. They are a generalization of matrices to an arbitrary number of dimensions.

In [4]:
# Create a scalar (0-dimensional tensor)
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [7]:
# Get the number of dimensions of the scalar
print(scalar.ndim)

# Get the number of elements in the scalar
print(scalar.item())

# Get the shape of the scalar
print(scalar.shape)

0
7
torch.Size([])


Vector is a 1-dimensional tensor with more than one element.

In [9]:
vector = torch.tensor([7, 7])
print(vector)
print(vector.ndim)

tensor([7, 7])
1


In [10]:
vector.shape

torch.Size([2])

Matrix is a 2-dimensional tensor.

In [11]:
MATRIX = torch.tensor([[7, 8], [9, 10]])

print(MATRIX)

tensor([[ 7,  8],
        [ 9, 10]])


In [12]:
MATRIX.ndim

2

In [13]:
MATRIX.shape

torch.Size([2, 2])

TENSOR with more than 2 dimensions is often referred to as a tensor of higher dimensions. For example, a 3-dimensional tensor can be thought of as a cube of numbers.

In [ ]:
TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])

In [16]:
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [15]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [20]:
TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])

In [21]:
TENSOR.ndim

3

In [22]:
TENSOR.shape

torch.Size([1, 3, 3])

In [23]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

# RANDOM TENSORS
Random tensors are tensors that are filled with random numbers. They are often used to initialize the weights of a neural network before training. So, after training, the random numbers will be updated to values that better represent the patterns in the data.

In [24]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)

In [26]:
print(random_tensor)

tensor([[0.2846, 0.5533, 0.8806, 0.0898],
        [0.6842, 0.7804, 0.8255, 0.4231],
        [0.1310, 0.1866, 0.9448, 0.4489]])


In [27]:
random_tensor.ndim

2

In [28]:
random_tensor.shape

torch.Size([3, 4])

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size=(224, 224, 3))  # height, width, color channels

In [32]:
random_image_tensor.ndim, random_image_tensor.shape

(3, torch.Size([224, 224, 3]))

In [35]:
# Zeros and Ones
# Create a tensor of all zeros or ones. This is useful when you want to create a tensor of a specific size but don't care about the values (e.g. for embedding layers, padding, etc.)

zeros = torch.zeros(size=(3, 4))
ones = torch.ones(size=(3, 4))

print(zeros)
print(ones)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [36]:
zeros.dtype, ones.dtype

(torch.float32, torch.float32)

# Tensor Range

In [42]:
range_tensor = torch.arange(start=1, end=11, step=1)

In [43]:
range_tensor, range_tensor.dtype, range_tensor.ndim, range_tensor.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 torch.int64,
 1,
 torch.Size([10]))

# Tensor Data Types

**Note:** The biggest erros when working with PyTorch are:
- 1. Tensor with incorrect data type,
- 2. Tensors with incorrect shape,
- 3. Tensors with incorrect device.

In [ ]:
float_tensor = torch.tensor(
    [3.0, 6.0, 9.0],
    dtype=torch.float16,  # what dtype is the tensor
    device=None,  # what device is the tensor on (GPU or CPU)
    requires_grad=False,  # whether or not to track gradients with this tensor. This is important for machine learning, if you set requires_grad=True, PyTorch will keep track of all operations on the tensor
    # and allow you to calculate gradients for optimization.
)

In [47]:
float_tensor

tensor([3., 6., 9.], dtype=torch.float16)